export const LISTAR_MENU_PERFIL_FIND_BY_ID_PERFIL = 'LISTAR_MENU_PERFIL_FIND_BY_ID_PERFIL';
export const LISTAR_NOTIFICACION_FIND_BY_ID_USER = 'LISTAR_NOTIFICACION_FIND_BY_ID_USER';
export const NOTIFICACIONES_FIND_ALL = 'NOTIFICACIONES_FIND_ALL';
