interface AppConfig {
    urlAlfresco: string;
    nombreUsuarioAlfresco: string;
    contrasenaAlfresco: string;
    nombreDelAgno: string;
    formatoAceite: JSON;
    formatoHarina: JSON;
    formatoPesca: JSON;
    docAceite: JSON;
    docHarina: JSON;
    docPescado: JSON;

    tupa03DocDato1:string;
    tupa03DocDato2:string;
    tupa03DocDato3:string;
    tupa04DocDato1:string;
    tupa07DocDato1:string;
    tupa07DocDato2:string;
    tupa07DocDato3:string;
    baseInformeFiscalizacion:string;
    medianteActaFiscalizacion:string;
    tupa08DocDato2:string;
    tupa08DocDato3:string;
    tupa09DocDato1:string;
    tupa09DocDato2:string;
    tupa09DocDato3:string;
    tupa09DocDato4:string;
    tupa10DocDato1:string;
    tupa10DocDato2:string;
    tupa10DocDato3:string;
    tupa10DocDato4:string;
    tupa17DocDato1:string;
    tupa20DocDato1:string;
    tupa21DocDato1:string;
    tupa21DocDato2:string;
    medianteActa:string;
    tupa24DocDato1:string;
    tupa24DocDato2:string;
    tupa24DocDato3:string;
    tupa24DocDato4:string;
    tupa07DocDato4:string;
    tupa07DocDato5:string;
    tupa08DocDato4:string;
    tupa08DocDato5:string;
    tupa08DocDato6:string;
    tupa09DocDato5:string;
    Tupa09DocDato6:string;
    conEficiencia:string;
    seExpideElPresente:string;
    reglamentoSectorial:string;
    autorizacionInstalacion:string;
    ley30063:string;
    ley27444:string;
    informeSanitario:string;
    informeSanitario2:string;
    asuntoInformeProtocolo:string;
    asuntoInformeCierre:string;
    asuntoInformeHaccp:string;
    asuntoInformeSanitario:string;
    cuerpoObservacionesTecnicas:string;
    cuerpoOficinaStandard:string;
    cuerpoFechaAuditoria1:string;
    cuerpoFechaAuditoria2:string;
    tupa09DescargaBivalvos:string;
    articulo26:string;
    tupa09DescargaBivalvos2:string;
    tupa09MuelleSistemaDescarga:string;
    tupa09MuelleSistemaDescarga2:string;
    tupa10:string;
    tupa10DocDato5:string;
    tupa11DocDato1:string;
    tupa12DocDato1:string;
    tupa12DocDato2:string;
    tupa13DocDato2:string;
    tupa13DocDato3:string;
    tupa13DocDato4:string;
    tupa13DocDato5:string;
    tupa13DocDato6:string;
    tupa15DocDato1:string;
    tupa15DocDato2:string;
    tupa17DocDato2:string;
    tupa17DocDato3:string;
    tupa17DocDato4:string;
    tupa20DocDato2:string;
    tupa21DocDato3:string;
    tupa21DocDato4:string;
    normativaSanitaria:string;
    tupa22DocDato1:string;
    tupa23DocDato1:string;
    tupa24DocDato5:string;
    tupa24DocDato6:string;
    tupa24DocDato7:string;
    tupa24DocDato8:string;
    tupa24DocDato9:string;
    tupa07DocDato6:string;
    tupa07DocDato7:string;
    tupa08DocDato1:string;
    tupa08DocDato7:string;
    tupa09DocDato6:string;
    tupa09DocDato7:string;
    tupa09DocDato8:string;
    tupa10y15:string;
    tupa11DocDato3:string;
    tupa12DocDato3:string;
    tupa13DocDato7:string;
    tupa13DocDato8:string;
    tupa13DocDato9:string;
    tupa21DocDato5:string;
    tupa21DocDato6:string;
    tupa22DocDato2:string;
    medioDePreservacion:string;
    tupa22y23:string;
    tupa24PermisoPesca:string;
    tupa24HabilitacionSanitaria:string;
    tupa24HabilitacionSanitaria2:string;
    tupa22Alcance:string;
    maxItemsPerPage: number;
    enableFeatureX: boolean;
  }
  
  export default AppConfig;